// Generated by EvelentScript 2.7.0
(function() {
  // This **Browser** compatibility layer extends core EvelentScript functions
  // to make things work smoothly when compiling code directly in the browser.
  // We add support for loading remote EvelentScript files via **XHR**, and
  // `text/evelentscript` script tags, source maps via data-URLs, and so on.
  var EvelentScript, compile,
    indexOf = [].indexOf;

  EvelentScript = require('./evelentscript');

  ({compile} = EvelentScript);

  // Use `window.eval` to evaluate code, rather than just `eval`, to run the
  // script in a clean global scope rather than inheriting the scope of the
  // EvelentScript compiler. (So that `cake test:browser` also works in Node,
  // use either `window.eval` or `global.eval` as appropriate).
  EvelentScript.eval = function(code, options = {}) {
    var globalRoot;
    if (options.bare == null) {
      options.bare = true;
    }
    globalRoot = typeof window !== "undefined" && window !== null ? window : global;
    return globalRoot['eval'](compile(code, options));
  };

  // Running code does not provide access to this scope.
  EvelentScript.run = function(code, options = {}) {
    options.bare = true;
    options.shiftLine = true;
    return Function(compile(code, options))();
  };

  // Export this more limited `EvelentScript` than what is exported by
  // `index.es`, which is intended for a Node environment.
  module.exports = EvelentScript;

  // If we’re not in a browser environment, we’re finished with the public API.
  if (typeof window === "undefined" || window === null) {
    return;
  }

  // Include source maps where possible. If we’ve got a base64 encoder, a
  // JSON serializer, and tools for escaping unicode characters, we’re good to go.
  // Ported from https://developer.mozilla.org/en-US/docs/DOM/window.btoa
  if ((typeof btoa !== "undefined" && btoa !== null) && (typeof JSON !== "undefined" && JSON !== null)) {
    compile = function(code, options = {}) {
      options.inlineMap = true;
      return EvelentScript.compile(code, options);
    };
  }

  // Load a remote script from the current domain via XHR.
  EvelentScript.load = function(url, callback, options = {}, hold = false) {
    var xhr;
    options.sourceFiles = [url];
    xhr = window.ActiveXObject ? new window.ActiveXObject('Microsoft.XMLHTTP') : new window.XMLHttpRequest();
    xhr.open('GET', url, true);
    if ('overrideMimeType' in xhr) {
      xhr.overrideMimeType('text/plain');
    }
    xhr.onreadystatechange = function() {
      var param, ref;
      if (xhr.readyState === 4) {
        if ((ref = xhr.status) === 0 || ref === 200) {
          param = [xhr.responseText, options];
          if (!hold) {
            EvelentScript.run(...param);
          }
        } else {
          throw new Error(`Could not load ${url}`);
        }
        if (callback) {
          return callback(param);
        }
      }
    };
    return xhr.send(null);
  };

  // Activate EvelentScript in the browser by having it compile and evaluate
  // all script tags with a content-type of `text/evelentscript`.
  // This happens on page load.
  EvelentScript.runScripts = function() {
    var esScripts, execute, i, index, j, len, s, script, scriptTypes, scripts;
    scripts = window.document.getElementsByTagName('script');
    scriptTypes = ['text/evelentscript', 'text/literate-evelentscript'];
    esScripts = (function() {
      var j, len, ref, results;
      results = [];
      for (j = 0, len = scripts.length; j < len; j++) {
        s = scripts[j];
        if (ref = s.type, indexOf.call(scriptTypes, ref) >= 0) {
          results.push(s);
        }
      }
      return results;
    })();
    index = 0;
    execute = function() {
      var param;
      param = esScripts[index];
      if (param instanceof Array) {
        EvelentScript.run(...param);
        index++;
        return execute();
      }
    };
    for (i = j = 0, len = esScripts.length; j < len; i = ++j) {
      script = esScripts[i];
      (function(script, i) {
        var options, source;
        options = {
          literate: script.type === scriptTypes[1]
        };
        source = script.src || script.getAttribute('data-src');
        if (source) {
          options.filename = source;
          return EvelentScript.load(source, function(param) {
            esScripts[i] = param;
            return execute();
          }, options, true);
        } else {
          // `options.filename` defines the filename the source map appears as
          // in Developer Tools. If a script tag has an `id`, use that as the
          // filename; otherwise use `evelentscript`, or `evelentscript1` etc.,
          // leaving the first one unnumbered for the common case that there’s
          // only one EvelentScript script block to parse.
          options.filename = script.id && script.id !== '' ? script.id : `evelentscript${i !== 0 ? i : ''}`;
          options.sourceFiles = ['embedded'];
          return esScripts[i] = [script.innerHTML, options];
        }
      })(script, i);
    }
    return execute();
  };

  // Listen for window load, both in decent browsers and in IE.
  // Only attach this event handler on startup for the
  // non-ES module version of the browser compiler, to preserve
  // backward compatibility while letting the ES module version
  // be importable without side effects.
  if (this === window) {
    if (window.addEventListener) {
      window.addEventListener('DOMContentLoaded', EvelentScript.runScripts, false);
    } else {
      window.attachEvent('onload', EvelentScript.runScripts);
    }
  }

}).call(this);
