// Generated by EvelentScript 2.7.0
(function() {
  // Project build: esconfig.json → compiled JavaScript in outDir (mirror or bundle).
  var DYNAMIC_IMPORT_RE, EXPORT_FROM_RE, EvelentScript, IMPORT_RE, REQUIRE_LINE_RE, compileOne, compileOptions, esconfig, fail, fs, getModuleSpecifiers, helpers, jsOutputPath, log, mkdirp, path, readSource, resolveLocalModule, sortDependencyOrder, stripExports, stripLocalImports, stripLocalRequires, useWinPathSep, writeOutput;

  fs = require('fs');

  path = require('path');

  helpers = require('./helpers');

  EvelentScript = require('./evelentscript');

  esconfig = require('./esconfig');

  useWinPathSep = path.sep === '\\';

  IMPORT_RE = /^import\s+(?:[\w\*\s{},.]+\s+from\s+)?['"]([^'"]+)['"]\s*;?\s*$/gm;

  EXPORT_FROM_RE = /^export\s+(?:\{[^}]*\}|\*(?:\s+as\s+[\w$]+)?)\s+from\s+['"]([^'"]+)['"]\s*;?\s*$/gm;

  DYNAMIC_IMPORT_RE = /import\s*\(\s*['"]([^'"]+)['"]\s*\)/g;

  log = function(message) {
    return console.log(message);
  };

  fail = function(message) {
    console.error(message);
    return process.exit(1);
  };

  mkdirp = function(dir) {
    if (!fs.existsSync(dir)) {
      return fs.mkdirSync(dir, {
        recursive: true
      });
    }
  };

  jsOutputPath = function(sourceFile, rootDir, outDir) {
    var base, dir, outRel, rel;
    rel = path.relative(rootDir, sourceFile);
    base = helpers.baseFileName(rel, true, useWinPathSep);
    dir = path.dirname(rel);
    outRel = dir === '.' ? base + '.js' : path.join(dir, base + '.js');
    return path.join(outDir, outRel);
  };

  readSource = function(file) {
    var raw;
    raw = fs.readFileSync(file, 'utf8');
    if (raw.charCodeAt(0) === 0xFEFF) {
      raw = raw.substring(1);
    }
    if (helpers.isLiterate(file)) {
      return helpers.invertLiterate(raw);
    } else {
      return raw;
    }
  };

  getModuleSpecifiers = function(code) {
    var collect, specs;
    specs = [];
    collect = function(re) {
      return code.replace(re, function(_, spec) {
        specs.push(spec);
        return '';
      });
    };
    collect(IMPORT_RE);
    collect(EXPORT_FROM_RE);
    collect(DYNAMIC_IMPORT_RE);
    return specs;
  };

  resolveLocalModule = function(specifier, fromFile, rootDir, sourceSet) {
    var candidate, candidates, fromDir, j, len, requested, resolved;
    if (!specifier.startsWith('.')) {
      return null;
    }
    fromDir = path.dirname(fromFile);
    requested = path.resolve(fromDir, specifier);
    candidates = [];
    if (/\.js$/i.test(specifier)) {
      candidates.push(requested.replace(/\.js$/i, '.es'));
    }
    candidates.push(requested);
    candidates.push(requested + '.es');
    candidates.push(path.join(requested, 'index.es'));
    for (j = 0, len = candidates.length; j < len; j++) {
      candidate = candidates[j];
      resolved = path.resolve(candidate);
      if (sourceSet.has(resolved)) {
        return resolved;
      }
    }
    return null;
  };

  REQUIRE_LINE_RE = /^[^\n]*require\s+['"](\.[^'"]+)['"][^\n]*$/gm;

  stripLocalRequires = function(code, fromFile, rootDir, sourceSet) {
    return code.replace(REQUIRE_LINE_RE, function(line, spec) {
      if (resolveLocalModule(spec, fromFile, rootDir, sourceSet)) {
        return '';
      } else {
        return line;
      }
    });
  };

  stripLocalImports = function(code, fromFile, rootDir, sourceSet) {
    var strip;
    strip = function(re) {
      return code = code.replace(re, function(line, spec) {
        if (resolveLocalModule(spec, fromFile, rootDir, sourceSet)) {
          return '';
        } else {
          return line;
        }
      });
    };
    code = strip(IMPORT_RE);
    code = strip(EXPORT_FROM_RE);
    return stripLocalRequires(code, fromFile, rootDir, sourceSet);
  };

  stripExports = function(code) {
    return code.replace(/^export\s+default\s+/gm, '').replace(/^export\s+/gm, '');
  };

  sortDependencyOrder = function(entry, rootDir, sourceSet) {
    var entryResolved, order, visit, visited, visiting;
    order = [];
    visiting = {};
    visited = {};
    visit = function(file) {
      var code, dep, j, len, ref, resolved, spec;
      resolved = path.resolve(file);
      if (visited[resolved]) {
        return;
      }
      if (visiting[resolved]) {
        throw new Error(`Circular dependency involving ${resolved}`);
      }
      visiting[resolved] = true;
      code = readSource(resolved);
      ref = getModuleSpecifiers(code);
      for (j = 0, len = ref.length; j < len; j++) {
        spec = ref[j];
        dep = resolveLocalModule(spec, resolved, rootDir, sourceSet);
        if (dep != null) {
          visit(dep);
        }
      }
      delete visiting[resolved];
      visited[resolved] = true;
      return order.push(resolved);
    };
    entryResolved = path.resolve(entry);
    if (!sourceSet.has(entryResolved)) {
      throw new Error(`Entry file is not part of the project: ${entryResolved}`);
    }
    visit(entryResolved);
    return order;
  };

  compileOptions = function(opts, filename, jsPath = null) {
    var answer;
    answer = {
      filename: filename,
      literate: helpers.isLiterate(filename),
      bare: opts.bare,
      header: opts.header,
      sourceMap: opts.sourceMap
    };
    if (opts.sourceMap && (jsPath != null)) {
      answer = {
        filename: filename,
        literate: answer.literate,
        bare: opts.bare,
        header: opts.header,
        sourceMap: true,
        generatedFile: helpers.baseFileName(jsPath, false, useWinPathSep),
        sourceFiles: [filename]
      };
    }
    return answer;
  };

  writeOutput = function(jsPath, js, sourceMap = null) {
    var mapPath;
    mkdirp(path.dirname(jsPath));
    if (sourceMap != null) {
      mapPath = `${jsPath}.map`;
      js = `${js}\n//# sourceMappingURL=${helpers.baseFileName(mapPath, false, useWinPathSep)}\n`;
      fs.writeFileSync(mapPath, sourceMap);
    }
    return fs.writeFileSync(jsPath, js);
  };

  compileOne = function(sourceFile, jsPath, opts) {
    var code, js, options, result;
    code = readSource(sourceFile);
    options = compileOptions(opts, sourceFile, jsPath);
    result = EvelentScript.compile(code, options);
    if (opts.sourceMap) {
      return writeOutput(jsPath, result.js, result.v3SourceMap);
    } else {
      js = typeof result === 'string' ? result : result.js;
      return writeOutput(jsPath, js);
    }
  };

  exports.buildProject = function(config) {
    var code, entry, file, j, js, jsPath, k, len, len1, merged, options, order, outPath, parts, result, source, sourceSet, sources;
    sources = esconfig.collectSources(config);
    sourceSet = new Set(sources.map(function(f) {
      return path.resolve(f);
    }));
    if (config.bundle) {
      entry = path.resolve(config.entry);
      if (!fs.existsSync(entry)) {
        throw new Error(`Entry file not found: ${entry}`);
      }
      order = sortDependencyOrder(entry, config.rootDir, sourceSet);
      parts = [];
      for (j = 0, len = order.length; j < len; j++) {
        file = order[j];
        code = readSource(file);
        if (file !== entry) {
          code = stripExports(code);
        }
        code = stripLocalImports(code, file, config.rootDir, sourceSet);
        parts.push(code);
      }
      merged = parts.join('\n\n');
      outPath = path.join(config.outDir, config.outFile);
      options = compileOptions(config, entry);
      if (config.bare !== false) {
        options.bare = true;
      }
      result = EvelentScript.compile(merged, options);
      js = typeof result === 'string' ? result : result.js;
      writeOutput(outPath, js);
      log(`bundled ${order.length} file(s) → ${outPath}`);
      return {
        files: order.length,
        outPath
      };
    }
    if (sources.length === 0) {
      throw new Error(`No EvelentScript source files found under ${config.rootDir}`);
    }
    for (k = 0, len1 = sources.length; k < len1; k++) {
      source = sources[k];
      jsPath = jsOutputPath(source, config.rootDir, config.outDir);
      compileOne(source, jsPath, config);
    }
    log(`compiled ${sources.length} file(s) → ${config.outDir}`);
    return {
      files: sources.length,
      outDir: config.outDir
    };
  };

  exports.run = function(args = []) {
    var config, configPath, doBuild, i, j, len, results, schedule, source, sources, timeout, watch;
    configPath = null;
    watch = false;
    i = 0;
    while (i < args.length) {
      switch (args[i]) {
        case '-w':
        case '--watch':
          watch = true;
          i += 1;
          break;
        case '-c':
        case '--config':
          configPath = args[i + 1];
          if (configPath == null) {
            fail('--config requires a path');
          }
          i += 2;
          break;
        case '-h':
        case '--help':
          console.log(`Usage: es build [options]

  Read esconfig.json and compile the project.

Options:
  -c, --config PATH   Path to esconfig.json (default: search upward from cwd)
  -w, --watch         Rebuild when source files change
  -h, --help          Show this help message

esconfig.json (compilerOptions):

  rootDir     Source root (default: ".")
  outDir      Output directory (default: "dist")
  entry       Entry file for bundle mode (default: "index.es")
  bundle      true = single outFile; false = mirror tree (default: false)
  outFile     Bundle output filename (default: "index.js")
  bare        Compile without function wrapper
  sourceMap   Emit .js.map files (project mode only)
  include     Glob patterns (default: **/*.es, etc.)
  exclude     Glob patterns (default: node_modules, outDir)`);
          return;
        default:
          fail(`Unknown option: ${args[i]}`);
      }
    }
    config = esconfig.load(configPath);
    doBuild = function() {
      var err, ref, ref1;
      try {
        return exports.buildProject(config);
      } catch (error) {
        err = error;
        return fail((ref = (ref1 = err.stack) != null ? ref1 : err.message) != null ? ref : err);
      }
    };
    if (watch) {
      log(`watching ${config.rootDir}...`);
      doBuild();
      timeout = null;
      schedule = function() {
        clearTimeout(timeout);
        return timeout = setTimeout(doBuild, 100);
      };
      sources = esconfig.collectSources(config);
      results = [];
      for (j = 0, len = sources.length; j < len; j++) {
        source = sources[j];
        results.push(fs.watch(source, schedule));
      }
      return results;
    } else {
      return doBuild();
    }
  };

}).call(this);
