// Generated by EvelentScript 2.7.0
(function() {
  // Load and normalize esconfig.json (TypeScript-style project config for EvelentScript).
  var CONFIG_NAMES, DEFAULT_COMPILER_OPTIONS, DEFAULT_EXCLUDE, DEFAULT_INCLUDE, findConfigFile, findDefaultEntry, fs, globToRegex, helpers, loadJson, normalizeOptions, path;

  fs = require('fs');

  path = require('path');

  helpers = require('./helpers');

  CONFIG_NAMES = ['esconfig.json', 'esconfig.jsonc'];

  DEFAULT_INCLUDE = ['*.es', '**/*.es', '*.lites', '**/*.lites', '*.es.md', '**/*.es.md'];

  DEFAULT_EXCLUDE = ['**/node_modules/**', '**/.git/**'];

  DEFAULT_COMPILER_OPTIONS = {
    rootDir: '.',
    outDir: 'dist',
    entry: 'index.es',
    bundle: false,
    outFile: 'index.js',
    bare: false,
    sourceMap: false,
    header: false,
    include: DEFAULT_INCLUDE,
    exclude: DEFAULT_EXCLUDE
  };

  findConfigFile = function(startDir) {
    var candidate, dir, i, len, name, parent;
    dir = path.resolve(startDir);
    while (true) {
      for (i = 0, len = CONFIG_NAMES.length; i < len; i++) {
        name = CONFIG_NAMES[i];
        candidate = path.join(dir, name);
        if (fs.existsSync(candidate)) {
          return candidate;
        }
      }
      parent = path.dirname(dir);
      if (parent === dir) {
        break;
      }
      dir = parent;
    }
    return null;
  };

  loadJson = function(filePath) {
    var raw;
    raw = fs.readFileSync(filePath, 'utf8');
    // Allow // and /* */ comments in esconfig.jsonc-style files.
    raw = raw.replace(/\/\/[^\n]*/g, '');
    raw = raw.replace(/\/\*[\s\S]*?\*\//g, '');
    return JSON.parse(raw);
  };

  normalizeOptions = function(raw, configDir) {
    var entryRel, flat, i, len, opts, pattern, ref, ref1, ref2, ref3, ref4, seen;
    flat = Object.assign({}, raw);
    if (raw.compilerOptions != null) {
      Object.assign(flat, raw.compilerOptions);
      delete flat.compilerOptions;
    }
    opts = Object.assign({}, DEFAULT_COMPILER_OPTIONS, flat);
    opts.rootDir = path.resolve(configDir, (ref = (ref1 = opts.rootDir) != null ? ref1 : opts.inputDir) != null ? ref : '.');
    opts.outDir = path.resolve(configDir, (ref2 = (ref3 = opts.outDir) != null ? ref3 : opts.outputDir) != null ? ref2 : 'dist');
    if (opts.entry != null) {
      entryRel = opts.entry;
      opts.entry = path.isAbsolute(entryRel) ? entryRel : path.resolve(opts.rootDir, entryRel);
    } else {
      opts.entry = findDefaultEntry(opts.rootDir);
    }
    if (flat.include != null) {
      seen = {};
      opts.include = [];
      ref4 = DEFAULT_INCLUDE.concat(flat.include);
      for (i = 0, len = ref4.length; i < len; i++) {
        pattern = ref4[i];
        if (!seen[pattern]) {
          seen[pattern] = true;
          opts.include.push(pattern);
        }
      }
    } else {
      opts.include = DEFAULT_INCLUDE.slice();
    }
    if (opts.exclude == null) {
      opts.exclude = DEFAULT_EXCLUDE;
    }
    opts.exclude = opts.exclude.concat([path.relative(opts.rootDir, opts.outDir).replace(/\\/g, '/') + '/**']);
    opts.configPath = null;
    opts.configDir = configDir;
    return opts;
  };

  findDefaultEntry = function(rootDir) {
    var candidate, i, len, name, ref;
    ref = ['index.es', 'main.es', 'app.es'];
    for (i = 0, len = ref.length; i < len; i++) {
      name = ref[i];
      candidate = path.join(rootDir, name);
      if (fs.existsSync(candidate)) {
        return candidate;
      }
    }
    return path.join(rootDir, 'index.es');
  };

  exports.findConfigFile = findConfigFile;

  exports.load = function(configPath = null, cwd = process.cwd()) {
    var configDir, opts, raw;
    if (configPath == null) {
      configPath = findConfigFile(cwd);
    }
    if (configPath == null) {
      throw new Error('Could not find esconfig.json in this directory or any parent directory.');
    }
    configDir = path.dirname(path.resolve(configPath));
    raw = loadJson(configPath);
    opts = normalizeOptions(raw, configDir);
    opts.configPath = path.resolve(configPath);
    return opts;
  };

  exports.matchesGlob = function(relPath, pattern) {
    var normalized, regex;
    normalized = relPath.replace(/\\/g, '/');
    regex = globToRegex(pattern.replace(/\\/g, '/'));
    return regex.test(normalized);
  };

  globToRegex = function(pattern) {
    var body, escaped, normalized, optionalPrefix;
    normalized = pattern.replace(/\\/g, '/');
    optionalPrefix = false;
    if (normalized.indexOf('**/') === 0) {
      optionalPrefix = true;
      normalized = normalized.substring(3);
    }
    escaped = normalized.replace(/[.+^${}()|[\]\\]/g, '\\$&');
    escaped = escaped.replace(/\*\*/g, '.*');
    escaped = escaped.replace(/\*/g, '[^/]*');
    escaped = escaped.replace(/\?/g, '[^/]');
    body = optionalPrefix ? `(?:.*/)?${escaped}` : escaped;
    return new RegExp(`^${body}$`);
  };

  exports.matchesAny = function(relPath, patterns) {
    var i, len, pattern;
    for (i = 0, len = patterns.length; i < len; i++) {
      pattern = patterns[i];
      if (exports.matchesGlob(relPath, pattern)) {
        return true;
      }
    }
    return false;
  };

  exports.collectSources = function(opts) {
    var files, walk;
    files = [];
    if (!fs.existsSync(opts.rootDir)) {
      throw new Error(`rootDir does not exist: ${opts.rootDir}`);
    }
    walk = function(dir) {
      var entry, full, i, len, name, ref, rel, results;
      ref = fs.readdirSync(dir, {
        withFileTypes: true
      });
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        entry = ref[i];
        name = entry.name;
        if (name === '.' || name === '..') {
          continue;
        }
        full = path.join(dir, name);
        rel = path.relative(opts.rootDir, full).replace(/\\/g, '/');
        if (entry.isDirectory()) {
          if (exports.matchesAny(rel + '/', opts.exclude)) {
            continue;
          }
          if (exports.matchesAny(rel + '/**', opts.exclude)) {
            continue;
          }
          results.push(walk(full));
        } else if (helpers.isEvelentScript(full)) {
          if (exports.matchesAny(rel, opts.exclude)) {
            continue;
          }
          if (!exports.matchesAny(rel, opts.include)) {
            continue;
          }
          results.push(files.push(full));
        } else {
          results.push(void 0);
        }
      }
      return results;
    };
    walk(opts.rootDir);
    return files.sort();
  };

}).call(this);
