// Generated by EvelentScript 2.7.0
(function() {
  // Type syntax nodes for EvelentScript.
  // Parsed type expressions compile away in JavaScript output and can be emitted
  // as TypeScript for static checking via `es --check-types`.
  var ArrayType, FunctionType, InterfaceDeclaration, InterfaceMember, IntersectionType, OptionalType, TypeAliasDeclaration, TypeBase, TypeParameter, TypeReference, UnionType, compact, flatten, fragmentsToText;

  ({compact, flatten, fragmentsToText} = require('./helpers'));

  exports.makeTypeReference = function(name, typeArguments = null) {
    return new exports.TypeReference(name, typeArguments);
  };

  exports.makeFunctionType = function(params, returnType) {
    return new exports.FunctionType(params, returnType);
  };

  //### TypeBase
  exports.TypeBase = TypeBase = class TypeBase {
    toTypeScript() {
      return '';
    }

    compileNode() {
      return [];
    }

    unwrap() {
      return this;
    }

    unfoldSoak() {
      return false;
    }

    isStatement() {
      return false;
    }

    jumps() {
      return false;
    }

    compileToFragments(o, lvl) {
      return this.compileNode(o);
    }

    compile(o, lvl) {
      return fragmentsToText(this.compileToFragments(o, lvl));
    }

    eachChild(func) {
      var attr, child, i, j, len, len1, ref, ref1;
      if (!this.children) {
        return this;
      }
      ref = this.children;
      for (i = 0, len = ref.length; i < len; i++) {
        attr = ref[i];
        if (this[attr]) {
          ref1 = flatten([this[attr]]);
          for (j = 0, len1 = ref1.length; j < len1; j++) {
            child = ref1[j];
            if (func(child) === false) {
              return this;
            }
          }
        }
      }
      return this;
    }

    updateLocationDataIfMissing(locationData, force) {
      if (force) {
        this.forceUpdateLocation = true;
      }
      if (this.locationData && !this.forceUpdateLocation) {
        return this;
      }
      delete this.forceUpdateLocation;
      this.locationData = locationData;
      this.eachChild(function(child) {
        return typeof child.updateLocationDataIfMissing === "function" ? child.updateLocationDataIfMissing(locationData) : void 0;
      });
      return this;
    }

    traverseChildren(crossScope, func) {
      this.eachChild(function(child) {
        var recur;
        recur = func(child);
        if (recur !== false) {
          return typeof child.traverseChildren === "function" ? child.traverseChildren(crossScope, func) : void 0;
        }
      });
      return this;
    }

  };

  //### TypeReference
  exports.TypeReference = TypeReference = (function() {
    class TypeReference extends exports.TypeBase {
      constructor(name1, typeArguments1 = null) {
        super();
        this.name = name1;
        this.typeArguments = typeArguments1;
      }

      toTypeScript() {
        var arg, args, base, ref;
        base = this.name instanceof exports.TypeBase ? this.name.toTypeScript() : `${this.name}`;
        if ((ref = this.typeArguments) != null ? ref.length : void 0) {
          args = ((function() {
            var i, len, ref1, results;
            ref1 = this.typeArguments;
            results = [];
            for (i = 0, len = ref1.length; i < len; i++) {
              arg = ref1[i];
              results.push(this.arg.toTypeScript());
            }
            return results;
          }).call(this)).join(', ');
          return `${base}<${args}>`;
        } else {
          return base;
        }
      }

    };

    TypeReference.prototype.children = ['typeArguments'];

    return TypeReference;

  }).call(this);

  //### UnionType
  exports.UnionType = UnionType = (function() {
    class UnionType extends exports.TypeBase {
      constructor(left, right) {
        super();
        this.left = left;
        this.right = right;
      }

      toTypeScript() {
        return `${this.left.toTypeScript()} | ${this.right.toTypeScript()}`;
      }

    };

    UnionType.prototype.children = ['left', 'right'];

    return UnionType;

  }).call(this);

  //### IntersectionType
  exports.IntersectionType = IntersectionType = (function() {
    class IntersectionType extends exports.TypeBase {
      constructor(left, right) {
        super();
        this.left = left;
        this.right = right;
      }

      toTypeScript() {
        return `${this.left.toTypeScript()} & ${this.right.toTypeScript()}`;
      }

    };

    IntersectionType.prototype.children = ['left', 'right'];

    return IntersectionType;

  }).call(this);

  //### OptionalType
  exports.OptionalType = OptionalType = (function() {
    class OptionalType extends exports.TypeBase {
      constructor(type) {
        super();
        this.type = type;
      }

      toTypeScript() {
        return `${this.type.toTypeScript()}?`;
      }

    };

    OptionalType.prototype.children = ['type'];

    return OptionalType;

  }).call(this);

  //### ArrayType
  exports.ArrayType = ArrayType = (function() {
    class ArrayType extends exports.TypeBase {
      constructor(elementType) {
        super();
        this.elementType = elementType;
      }

      toTypeScript() {
        return `${this.elementType.toTypeScript()}[]`;
      }

    };

    ArrayType.prototype.children = ['elementType'];

    return ArrayType;

  }).call(this);

  //### FunctionType
  exports.FunctionType = FunctionType = (function() {
    class FunctionType extends exports.TypeBase {
      constructor(params1 = [], returnType1 = null) {
        super();
        this.params = params1;
        this.returnType = returnType1;
      }

      toTypeScript() {
        var param, paramText, ref, ref1, ret;
        paramText = ((function() {
          var i, len, ref, results;
          ref = this.params;
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            param = ref[i];
            results.push(this.paramTypeText(param));
          }
          return results;
        }).call(this)).join(', ');
        ret = (ref = (ref1 = this.returnType) != null ? ref1.toTypeScript() : void 0) != null ? ref : 'void';
        return `(${paramText}): ${ret}`;
      }

      paramTypeText(param) {
        var name, optional, ref, ref1, ref2, ref3, ref4, typeText;
        name = (ref = (ref1 = (ref2 = param.name) != null ? ref2.value : void 0) != null ? ref1 : param.name) != null ? ref : '_';
        typeText = (ref3 = (ref4 = param.typeAnnotation) != null ? ref4.toTypeScript() : void 0) != null ? ref3 : 'any';
        optional = param.optional ? '?' : '';
        return `${name}${optional}: ${typeText}`;
      }

    };

    FunctionType.prototype.children = ['params', 'returnType'];

    return FunctionType;

  }).call(this);

  //### TypeParameter
  exports.TypeParameter = TypeParameter = class TypeParameter extends exports.TypeBase {
    constructor(name1, constraint = null, defaultType = null) {
      super();
      this.name = name1;
      this.constraint = constraint;
      this.defaultType = defaultType;
    }

    toTypeScript() {
      var ref, text;
      text = (ref = this.name.value) != null ? ref : this.name;
      if (this.constraint) {
        text += ` extends ${this.constraint.toTypeScript()}`;
      }
      if (this.defaultType) {
        text += ` = ${this.defaultType.toTypeScript()}`;
      }
      return text;
    }

  };

  //### TypeParameterList
  exports.typeParametersToTypeScript = function(params) {
    var p;
    if (!(params != null ? params.length : void 0)) {
      return '';
    }
    return `<${((function() {
      var i, len, results;
      results = [];
      for (i = 0, len = params.length; i < len; i++) {
        p = params[i];
        results.push(p.toTypeScript());
      }
      return results;
    })()).join(', ')}>`;
  };

  //### InterfaceMember
  exports.InterfaceMember = InterfaceMember = (function() {
    class InterfaceMember extends exports.TypeBase {
      constructor(name1, typeAnnotation, options = {}) {
        super();
        this.name = name1;
        this.typeAnnotation = typeAnnotation;
        this.optional = options.optional === true;
        this.readonly = options.readonly === true;
        this.method = options.method === true;
      }

      toTypeScript() {
        var name, optional, prefix, ref, ref1;
        prefix = this.readonly ? 'readonly ' : '';
        name = (ref = (ref1 = this.name.value) != null ? ref1 : this.name.name) != null ? ref : this.name;
        optional = this.optional && !this.method ? '?' : '';
        return `${prefix}${name}${optional}: ${this.typeAnnotation.toTypeScript()}`;
      }

    };

    InterfaceMember.prototype.children = ['name', 'typeAnnotation'];

    return InterfaceMember;

  }).call(this);

  //### InterfaceDeclaration
  exports.InterfaceDeclaration = InterfaceDeclaration = (function() {
    class InterfaceDeclaration extends exports.TypeBase {
      constructor(name1, typeParameters = [], extendsType = null, members = []) {
        super();
        this.name = name1;
        this.typeParameters = typeParameters;
        this.extendsType = extendsType;
        this.members = members;
      }

      isStatement() {
        return true;
      }

      jumps() {
        return false;
      }

      compileNode() {
        return [];
      }

      toTypeScript() {
        var body, head, member, params;
        params = exports.typeParametersToTypeScript(this.typeParameters);
        head = `interface ${this.name.value}${params}`;
        if (this.extendsType) {
          head += ` extends ${this.extendsType.toTypeScript()}`;
        }
        body = ((function() {
          var i, len, ref, results;
          ref = this.members;
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            member = ref[i];
            results.push(member.toTypeScript());
          }
          return results;
        }).call(this)).join('\n  ');
        if (body) {
          return `${head} {\n  ${body}\n}`;
        } else {
          return `${head} {}`;
        }
      }

    };

    InterfaceDeclaration.prototype.children = ['name', 'typeParameters', 'extendsType', 'members'];

    return InterfaceDeclaration;

  }).call(this);

  //### TypeAliasDeclaration
  exports.TypeAliasDeclaration = TypeAliasDeclaration = (function() {
    class TypeAliasDeclaration extends exports.TypeBase {
      constructor(name1, typeParameters = [], typeAnnotation) {
        super();
        this.name = name1;
        this.typeParameters = typeParameters;
        this.typeAnnotation = typeAnnotation;
      }

      isStatement() {
        return true;
      }

      jumps() {
        return false;
      }

      compileNode() {
        return [];
      }

      toTypeScript() {
        var params;
        params = exports.typeParametersToTypeScript(this.typeParameters);
        return `type ${this.name.value}${params} = ${this.typeAnnotation.toTypeScript()}`;
      }

    };

    TypeAliasDeclaration.prototype.children = ['name', 'typeParameters', 'typeAnnotation'];

    return TypeAliasDeclaration;

  }).call(this);

  //### TypeProgram
  exports.collectTypeDeclarations = function(body) {
    var declarations;
    declarations = [];
    body.traverseChildren(false, function(node) {
      if (node instanceof exports.InterfaceDeclaration || node instanceof exports.TypeAliasDeclaration) {
        return declarations.push(node);
      }
    });
    return declarations;
  };

  exports.emitTypeScriptDeclarations = function(nodes) {
    var node;
    return ((function() {
      var i, len, results;
      results = [];
      for (i = 0, len = nodes.length; i < len; i++) {
        node = nodes[i];
        results.push(node.toTypeScript());
      }
      return results;
    })()).join('\n\n');
  };

  exports.mergeTypeScriptWithJavaScript = function(js, declarations) {
    var header;
    header = exports.emitTypeScriptDeclarations(declarations);
    if (!header) {
      return js;
    }
    return `${header}\n\n${js}`;
  };

}).call(this);
