use crate::ast::*;
use std::collections::HashSet;

pub struct Codegen {
    indent: usize,
    bare: bool,
    declared: HashSet<String>,
}

impl Codegen {
    pub fn new(bare: bool) -> Self {
        Self {
            indent: 0,
            bare,
            declared: HashSet::new(),
        }
    }

    pub fn emit_program(&mut self, program: &Program) -> String {
        let mut out = String::new();
        if !self.bare {
            out.push_str("// Generated by esc (native EvelentScript)\n");
            out.push_str("(function() {\n");
            self.indent = 1;
        }
        for stmt in &program.body {
            out.push_str(&self.emit_stmt(stmt));
            if !out.ends_with('\n') {
                out.push('\n');
            }
        }
        if !self.bare {
            out.push_str("}).call(this);\n");
            self.indent = 0;
        }
        out
    }

    fn pad(&self) -> String {
        "  ".repeat(self.indent)
    }

    fn emit_stmt(&mut self, stmt: &Stmt) -> String {
        let pad = self.pad();
        match stmt {
            Stmt::Expr(e) => format!("{}{};\n", pad, self.emit_expr(e)),
            Stmt::Assign { target, value, op } => {
                format!(
                    "{}{};\n",
                    pad,
                    self.emit_assign(target, value, *op)
                )
            }
            Stmt::Return(None) => format!("{}return;\n", pad),
            Stmt::Return(Some(e)) => format!("{}return {};\n", pad, self.emit_expr(e)),
            Stmt::Break => format!("{}break;\n", pad),
            Stmt::Continue => format!("{}continue;\n", pad),
            Stmt::Throw(e) => format!("{}throw {};\n", pad, self.emit_expr(e)),
            Stmt::If {
                test,
                body,
                else_body,
                inverted,
            } => {
                let mut s = String::new();
                // Hoist assignment targets used in `if x = ...`
                if let Expr::AssignExpr {
                    target: AssignTarget::Ident(n),
                    ..
                } = test
                {
                    if self.declared.insert(n.clone()) {
                        s.push_str(&format!("{}let {};\n", pad, n));
                    }
                }
                let cond = if *inverted {
                    format!("!({})", self.emit_expr(test))
                } else {
                    self.emit_expr(test)
                };
                s.push_str(&format!("{}if ({}) {{\n", pad, cond));
                self.indent += 1;
                for st in body {
                    s.push_str(&self.emit_stmt(st));
                }
                self.indent -= 1;
                s.push_str(&format!("{}}}", pad));
                if let Some(els) = else_body {
                    s.push_str(" else {\n");
                    self.indent += 1;
                    for st in els {
                        s.push_str(&self.emit_stmt(st));
                    }
                    self.indent -= 1;
                    s.push_str(&format!("{}}}", pad));
                }
                s.push('\n');
                s
            }
            Stmt::While {
                test,
                body,
                inverted,
            } => {
                let cond = if *inverted {
                    format!("!({})", self.emit_expr(test))
                } else {
                    self.emit_expr(test)
                };
                let mut s = format!("{}while ({}) {{\n", pad, cond);
                self.indent += 1;
                for st in body {
                    s.push_str(&self.emit_stmt(st));
                }
                self.indent -= 1;
                s.push_str(&format!("{}}}\n", pad));
                s
            }
            Stmt::For {
                name,
                index,
                iter,
                body,
                own: _,
            } => {
                let iter_js = self.emit_expr(iter);
                let mut s = String::new();
                if let Some(idx) = index {
                    s.push_str(&format!(
                        "{}for (let {} = 0, __ref = {}; {} < __ref.length; {}++) {{\n",
                        pad, idx, iter_js, idx, idx
                    ));
                    self.indent += 1;
                    s.push_str(&format!("{}const {} = __ref[{}];\n", self.pad(), name, idx));
                } else {
                    s.push_str(&format!("{}for (const {} of {}) {{\n", pad, name, iter_js));
                    self.indent += 1;
                }
                for st in body {
                    s.push_str(&self.emit_stmt(st));
                }
                self.indent -= 1;
                s.push_str(&format!("{}}}\n", pad));
                s
            }
            Stmt::Class {
                name,
                superclass,
                body,
            } => {
                let extends = superclass
                    .as_ref()
                    .map(|e| format!(" extends {}", self.emit_expr(e)))
                    .unwrap_or_default();
                let mut s = format!("{}class {}{} {{\n", pad, name, extends);
                self.indent += 1;
                for item in body {
                    s.push_str(&self.emit_class_item(item));
                }
                self.indent -= 1;
                s.push_str(&format!("{}}}\n", pad));
                s
            }
            Stmt::Import(imp) => self.emit_import(imp),
            Stmt::Export(exp) => self.emit_export(exp),
            Stmt::Try {
                body,
                catch,
                finally,
            } => {
                let mut s = format!("{}try {{\n", pad);
                self.indent += 1;
                for st in body {
                    s.push_str(&self.emit_stmt(st));
                }
                self.indent -= 1;
                s.push_str(&format!("{}}}", pad));
                if let Some((name, cbody)) = catch {
                    let binding = name.clone().unwrap_or_else(|| "_e".into());
                    s.push_str(&format!(" catch ({binding}) {{\n"));
                    self.indent += 1;
                    for st in cbody {
                        s.push_str(&self.emit_stmt(st));
                    }
                    self.indent -= 1;
                    s.push_str(&format!("{}}}", pad));
                }
                if let Some(fbody) = finally {
                    s.push_str(" finally {\n");
                    self.indent += 1;
                    for st in fbody {
                        s.push_str(&self.emit_stmt(st));
                    }
                    self.indent -= 1;
                    s.push_str(&format!("{}}}", pad));
                }
                s.push('\n');
                s
            }
        }
    }

    fn emit_class_item(&mut self, item: &ClassItem) -> String {
        let pad = self.pad();
        match item {
            ClassItem::Method {
                name,
                params,
                body,
                is_static,
            } => {
                let st = if *is_static { "static " } else { "" };
                let ps = self.emit_params(params);
                let mut s = format!("{}{}{}({}) {{\n", pad, st, name, ps);
                self.indent += 1;
                for st in body {
                    s.push_str(&self.emit_stmt(st));
                }
                self.indent -= 1;
                s.push_str(&format!("{}}}\n", pad));
                s
            }
            ClassItem::Property {
                name,
                value,
                is_static,
            } => {
                let st = if *is_static { "static " } else { "" };
                format!("{}{}{} = {};\n", pad, st, name, self.emit_expr(value))
            }
        }
    }

    fn emit_import(&self, imp: &ImportDecl) -> String {
        let pad = self.pad();
        match imp {
            ImportDecl::SideEffect { source } => {
                format!("{}import {};\n", pad, js_string(source))
            }
            ImportDecl::Default { name, source } => {
                format!(
                    "{}import {} from {};\n",
                    pad,
                    name,
                    js_string(source)
                )
            }
            ImportDecl::Namespace { name, source } => {
                format!(
                    "{}import * as {} from {};\n",
                    pad,
                    name,
                    js_string(source)
                )
            }
            ImportDecl::Named { specs, source } => {
                let list = specs
                    .iter()
                    .map(|(imp, local)| {
                        if imp == local {
                            imp.clone()
                        } else {
                            format!("{imp} as {local}")
                        }
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                format!(
                    "{}import {{ {} }} from {};\n",
                    pad,
                    list,
                    js_string(source)
                )
            }
        }
    }

    fn emit_export(&mut self, exp: &ExportDecl) -> String {
        let pad = self.pad();
        match exp {
            ExportDecl::Default(e) => {
                format!("{}export default {};\n", pad, self.emit_expr(e))
            }
            ExportDecl::Named(specs) => {
                let list = specs
                    .iter()
                    .map(|(local, exported)| match exported {
                        Some(e) => format!("{local} as {e}"),
                        None => local.clone(),
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{}export {{ {} }};\n", pad, list)
            }
            ExportDecl::AllFrom(source) => {
                format!("{}export * from {};\n", pad, js_string(source))
            }
            ExportDecl::NamedFrom { specs, source } => {
                let list = specs
                    .iter()
                    .map(|(local, exported)| match exported {
                        Some(e) => format!("{local} as {e}"),
                        None => local.clone(),
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                format!(
                    "{}export {{ {} }} from {};\n",
                    pad,
                    list,
                    js_string(source)
                )
            }
            ExportDecl::Decl(stmt) => {
                let inner = self.emit_stmt(stmt);
                // prepend export to first line
                if let Some(rest) = inner.strip_prefix(&pad) {
                    format!("{pad}export {rest}")
                } else {
                    format!("{pad}export {inner}")
                }
            }
        }
    }

    fn emit_assign(&mut self, target: &AssignTarget, value: &Expr, op: AssignOp) -> String {
        let decl = matches!(op, AssignOp::Eq | AssignOp::ColonEq);
        self.emit_assign_inner(target, value, op, decl)
    }

    fn emit_assign_inner(
        &mut self,
        target: &AssignTarget,
        value: &Expr,
        op: AssignOp,
        allow_decl: bool,
    ) -> String {
        let op_s = match op {
            AssignOp::Eq | AssignOp::ColonEq => "=",
            AssignOp::PlusEq => "+=",
            AssignOp::MinusEq => "-=",
            AssignOp::StarEq => "*=",
            AssignOp::SlashEq => "/=",
        };
        match target {
            AssignTarget::Ident(n) => {
                let needs_decl = allow_decl && self.declared.insert(n.clone());
                if needs_decl {
                    format!("let {} {} {}", n, op_s, self.emit_expr(value))
                } else {
                    // Still register the name so later stmt assigns don't re-let
                    self.declared.insert(n.clone());
                    format!("{} {} {}", n, op_s, self.emit_expr(value))
                }
            }
            AssignTarget::Member {
                object,
                property,
                computed,
            } => {
                let obj = self.emit_expr(object);
                let access = if *computed {
                    format!("{}[{}]", obj, self.emit_expr(property))
                } else if let Expr::String(p) = &**property {
                    format!("{}.{}", obj, p)
                } else {
                    format!("{}[{}]", obj, self.emit_expr(property))
                };
                format!("{} {} {}", access, op_s, self.emit_expr(value))
            }
            AssignTarget::Array(targets) => {
                let names: Vec<String> = targets
                    .iter()
                    .map(|t| match t {
                        Some(AssignTarget::Ident(n)) => {
                            self.declared.insert(n.clone());
                            n.clone()
                        }
                        Some(_) => "_".into(),
                        None => "".into(),
                    })
                    .collect();
                if allow_decl {
                    format!("let [{}] = {}", names.join(", "), self.emit_expr(value))
                } else {
                    format!("[{}] = {}", names.join(", "), self.emit_expr(value))
                }
            }
            AssignTarget::Object(_) => {
                format!("/* object destructure */ ({})", self.emit_expr(value))
            }
        }
    }

    fn emit_expr(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::Ident(n) => n.clone(),
            Expr::Number(n) => n.clone(),
            Expr::String(s) => {
                if let Some(rest) = s.strip_prefix("__TPL__") {
                    format!("`{}`", rest.replace('`', "\\`"))
                } else {
                    js_string(s)
                }
            }
            Expr::Bool(b) => b.to_string(),
            Expr::Null => "null".into(),
            Expr::Undefined => "void 0".into(),
            Expr::This => "this".into(),
            Expr::Array(els) => {
                let inner = els
                    .iter()
                    .map(|e| self.emit_expr(e))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("[{inner}]")
            }
            Expr::Object(props) => {
                let inner = props
                    .iter()
                    .map(|(k, v)| {
                        let key = match k {
                            ObjectKey::Ident(n) => n.clone(),
                            ObjectKey::String(s) => js_string(s),
                            ObjectKey::Computed(e) => format!("[{}]", self.emit_expr(e)),
                        };
                        format!("{}: {}", key, self.emit_expr(v))
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("({{ {inner} }})")
            }
            Expr::Unary { op, arg } => {
                let a = self.emit_expr(arg);
                match op {
                    UnaryOp::Not => format!("!({})", a),
                    UnaryOp::Neg => format!("-({})", a),
                    UnaryOp::Pos => format!("+({})", a),
                    UnaryOp::TypeOf => format!("typeof ({})", a),
                    UnaryOp::Delete => format!("delete ({})", a),
                }
            }
            Expr::Binary { op, left, right } => {
                let l = self.emit_expr(left);
                let r = self.emit_expr(right);
                let o = match op {
                    BinaryOp::Add => "+",
                    BinaryOp::Sub => "-",
                    BinaryOp::Mul => "*",
                    BinaryOp::Div => "/",
                    BinaryOp::Mod => "%",
                    BinaryOp::Eq | BinaryOp::StrictEq => "===",
                    BinaryOp::NotEq | BinaryOp::StrictNotEq => "!==",
                    BinaryOp::Lt => "<",
                    BinaryOp::Gt => ">",
                    BinaryOp::LtEq => "<=",
                    BinaryOp::GtEq => ">=",
                    BinaryOp::And => "&&",
                    BinaryOp::Or => "||",
                };
                format!("({l} {o} {r})")
            }
            Expr::Call { callee, args } => {
                let c = self.emit_expr(callee);
                let a = args
                    .iter()
                    .map(|e| self.emit_expr(e))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{c}({a})")
            }
            Expr::Member {
                object,
                property,
                computed,
                optional,
            } => {
                let obj = self.emit_expr(object);
                let op = if *optional { "?." } else { "." };
                if *computed {
                    let idx = self.emit_expr(property);
                    if *optional {
                        format!("{obj}?[{idx}]")
                    } else {
                        format!("{obj}[{idx}]")
                    }
                } else if let Expr::String(p) = &**property {
                    format!("{obj}{op}{p}")
                } else {
                    format!("{obj}[{}]", self.emit_expr(property))
                }
            }
            Expr::Func {
                params,
                body,
                expression: _,
                bound,
                async_,
            } => {
                let async_kw = if *async_ { "async " } else { "" };
                let ps = self.emit_params(params);
                if *bound {
                    // fat arrow
                    let mut s = format!("{async_kw}({ps}) => {{\n");
                    self.indent += 1;
                    for st in body {
                        s.push_str(&self.emit_stmt(st));
                    }
                    self.indent -= 1;
                    s.push_str(&format!("{}}}", self.pad()));
                    s
                } else {
                    let mut s = format!("{async_kw}function({ps}) {{\n");
                    self.indent += 1;
                    for st in body {
                        s.push_str(&self.emit_stmt(st));
                    }
                    self.indent -= 1;
                    s.push_str(&format!("{}}}", self.pad()));
                    s
                }
            }
            Expr::New { callee, args } => {
                let c = self.emit_expr(callee);
                let a = args
                    .iter()
                    .map(|e| self.emit_expr(e))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("(new {c}({a}))")
            }
            Expr::Require(spec) => {
                if let Some(name) = spec.strip_prefix("native:") {
                    format!(
                        "(typeof __evelent_native !== 'undefined' ? __evelent_native.load({}) : require({}))",
                        js_string(name),
                        js_string(spec)
                    )
                } else {
                    format!("require({})", js_string(spec))
                }
            }
            Expr::SoakedCall { callee, args } => {
                let c = self.emit_expr(callee);
                let a = args
                    .iter()
                    .map(|e| self.emit_expr(e))
                    .collect::<Vec<_>>()
                    .join(", ");
                // CoffeeScript soak: call only if callee exists
                format!(
                    "(typeof {c} !== \"undefined\" && {c} !== null ? {c}({a}) : void 0)"
                )
            }
            Expr::Await(e) => format!("(await {})", self.emit_expr(e)),
            Expr::Existence(e) => format!("({} != null)", self.emit_expr(e)),
            Expr::ExistentialDefault { value, default } => {
                let v = self.emit_expr(value);
                let d = self.emit_expr(default);
                format!("({v} != null ? {v} : {d})")
            }
            Expr::AssignExpr { target, value, op } => {
                // Expression-context assignment never introduces `let`
                self.emit_assign_inner(target, value, *op, false)
            }
            Expr::IfExpr {
                test,
                then_branch,
                else_branch,
                inverted,
            } => {
                let cond = if *inverted {
                    format!("!({})", self.emit_expr(test))
                } else {
                    self.emit_expr(test)
                };
                let then_s = self.emit_expr(then_branch);
                let else_s = else_branch
                    .as_ref()
                    .map(|e| self.emit_expr(e))
                    .unwrap_or_else(|| "void 0".into());
                format!("({cond} ? {then_s} : {else_s})")
            }
            Expr::Block(stmts) => {
                let mut s = "(function() {\n".to_string();
                self.indent += 1;
                for (i, st) in stmts.iter().enumerate() {
                    if i + 1 == stmts.len() {
                        if let Stmt::Expr(e) = st {
                            s.push_str(&format!("{}return {};\n", self.pad(), self.emit_expr(e)));
                            continue;
                        }
                    }
                    s.push_str(&self.emit_stmt(st));
                }
                self.indent -= 1;
                s.push_str(&format!("{}}})()", self.pad()));
                s
            }
        }
    }

    fn emit_params(&mut self, params: &[Param]) -> String {
        params
            .iter()
            .map(|p| {
                let mut s = if p.rest {
                    format!("...{}", p.name)
                } else {
                    p.name.clone()
                };
                if let Some(d) = &p.default {
                    s.push_str(&format!(" = {}", self.emit_expr(d)));
                }
                s
            })
            .collect::<Vec<_>>()
            .join(", ")
    }
}

fn js_string(s: &str) -> String {
    let mut out = String::from("'");
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '\'' => out.push_str("\\'"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out.push('\'');
    out
}
