//! Native EvelentScript core: lexer → parser → **Rust VM** (and optional JS codegen).
//!
//! Primary path is in-process interpretation via [`Vm`] / [`run_file`].
//! JavaScript emit remains available for interop (`compile` / `build`).
//!
//! With `default-features = false`, only the JS codegen front-end is built
//! (used by Evelent Engine). Enable `full` for the VM, packages, and builtins.

pub mod ast;
pub mod codegen;
pub mod error;
pub mod lexer;
pub mod module;
pub mod parser;
pub mod token;

#[cfg(feature = "full")]
pub mod builtins;
#[cfg(feature = "full")]
pub mod config;
#[cfg(feature = "full")]
pub mod pkg;
#[cfg(feature = "full")]
pub mod runtime;
#[cfg(feature = "full")]
pub mod value;

#[cfg(feature = "full")]
pub use config::{
    collect_sources, find_config_file, load_config, load_from_cwd, out_path_for, ProjectConfig,
};
pub use error::{Error, Result};
pub use module::{
    compile_file, compile_graph, compile_source, CompileOptions, CompiledModule, ModuleGraph,
};
#[cfg(feature = "full")]
pub use module::NativeHost;
#[cfg(feature = "full")]
pub use pkg::{
    add_dependency, create_package, find_manifest, install_dependencies, load_from_cwd as load_pkg,
    registry_root, remove_dependency, resolve_package_lib, search_registry, Manifest, Package,
    Dependency, MANIFEST_NAME, MODULES_DIR,
};
#[cfg(feature = "full")]
pub use runtime::{run_file, Vm};
#[cfg(feature = "full")]
pub use value::Value;

/// Compile a string of EvelentScript to JavaScript.
pub fn compile(source: &str, filename: &str, bare: bool) -> Result<String> {
    let opts = CompileOptions {
        bare,
        ..Default::default()
    };
    Ok(compile_source(source, filename, &opts)?.js)
}

/// Compile every file matched by an `esconfig.json` project.
/// Returns `(written, errors)` — continues past per-file failures (tsc-style).
#[cfg(feature = "full")]
pub fn build_project(
    cfg: &ProjectConfig,
) -> Result<(Vec<(std::path::PathBuf, std::path::PathBuf)>, Vec<(std::path::PathBuf, String)>)> {
    let sources = collect_sources(cfg)?;
    let compile_opts = CompileOptions {
        bare: cfg.bare,
        native_dirs: if cfg.native_dirs.is_empty() {
            vec![std::path::PathBuf::from("native-modules")]
        } else {
            cfg.native_dirs.clone()
        },
    };

    let mut written = Vec::new();
    let mut errors = Vec::new();

    if cfg.bundle {
        let entry = cfg.entry.clone().ok_or_else(|| {
            Error::Other("bundle: true requires compilerOptions.entry".into())
        })?;
        match compile_graph(&entry, &compile_opts) {
            Ok(graph) => {
                std::fs::create_dir_all(&cfg.out_dir)?;
                let out_name = cfg
                    .out_file
                    .clone()
                    .unwrap_or_else(|| "index.js".into());
                let dest = cfg.out_dir.join(out_name);
                let mut bundle = String::from("// Generated by esc (bundled)\n");
                for path in &graph.order {
                    let compiled = &graph.modules[path];
                    bundle.push_str(&format!("\n// ---- {} ----\n", path.display()));
                    bundle.push_str(&compiled.js);
                    if !bundle.ends_with('\n') {
                        bundle.push('\n');
                    }
                }
                std::fs::write(&dest, bundle)?;
                written.push((entry, dest));
            }
            Err(e) => errors.push((entry, e.to_string())),
        }
        return Ok((written, errors));
    }

    for source in sources {
        match compile_file(&source, &compile_opts) {
            Ok(compiled) => {
                let dest = out_path_for(cfg, &source);
                if let Some(parent) = dest.parent() {
                    std::fs::create_dir_all(parent)?;
                }
                std::fs::write(&dest, &compiled.js)?;
                written.push((source, dest));
            }
            Err(e) => errors.push((source, e.to_string())),
        }
    }
    Ok((written, errors))
}
